sudo: false
language: node_js

node_js:
  - node

os:
  - osx
  - linux

services:
  - xvfb 

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent
  - npm run ui-test
