# Test against the latest version of this Node.js version
environment:
  nodejs_version: "12"


platform:
  - x64

# Install scripts. git a(runs after repo cloning)
install:
  # long path on win platform
  - md C:\npm-cache
  - npm config set cache C:\npm-cache
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
  - npm run ui-test

# Don't actually build.
build: off
